AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - '*.rb'
    - 'spec/**/*'
    - 'features/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - '*.gemspec'
    - 'bin/*'

Metrics/ClassLength:
  Max: 150

MethodLength:
  Max: 30

Documentation:
  Enabled: false

AndOr:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

# why use this option ?
#RedundantBegin:
#  Enabled: false

NumericLiterals:
  Enabled: false

CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

Next:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: [
    '^\s*#',
    'ruby wrapper for the Bitbucket REST API*'
  ]

Style/SymbolArray:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false
