version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ arch }}-{{ checksum "Gemfile" }}-{{ checksum "ogpr.gemspec" }}
          - dependency-cache
      - run:
          name: Install dependency
          command: |
            gem install -v 1.17.3 bundler
            bundle install --jobs=4 --retry=3 --path ./.bundle
      - save_cache:
          paths:
            - ./.bundle
          key: dependency-cache-{{ arch }}-{{ checksum "Gemfile" }}-{{ checksum "ogpr.gemspec" }}
      - run:
          name: Check lint
          command: bundle exec rake rubocop
      - run:
          name: Run unit test
          command: |
            bundle exec rake spec
            bundle exec codeclimate-test-reporter

workflows:
  version: 2
  build:
    jobs:
      - build
